"""numeric user IDs: admin123@gmail.com is 1, everyone else 2, 3, ...

Converts users.id (UUID string) to a sequential integer and remaps
tasks.owner_id, keeping all existing users and tasks. Existing users are
numbered by signup order starting at 2. ID 1 is reserved for the main admin:
if an admin123@gmail.com account already exists it becomes 1, otherwise the
app creates it with ID 1 on startup (app/seed.py).

PostgreSQL only (the test suite uses SQLite via create_all, not migrations).

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-02

"""
from alembic import op

revision = "0003"
down_revision = "0002"
branch_labels = None
depends_on = None

ROOT_ADMIN_EMAIL = "admin123@gmail.com"


def upgrade() -> None:
    if op.get_bind().dialect.name != "postgresql":
        raise RuntimeError("Migration 0003 supports PostgreSQL only.")

    # 1. Give every user a new integer id (1 reserved for the main admin).
    op.execute("ALTER TABLE users ADD COLUMN new_id INTEGER")
    op.execute(f"UPDATE users SET new_id = 1 WHERE lower(email) = '{ROOT_ADMIN_EMAIL}'")
    op.execute(
        """
        WITH numbered AS (
            SELECT id, ROW_NUMBER() OVER (ORDER BY created_at, id) + 1 AS n
            FROM users
            WHERE new_id IS NULL
        )
        UPDATE users u SET new_id = numbered.n FROM numbered WHERE u.id = numbered.id
        """
    )

    # 2. Point every task at its owner's new id.
    op.execute("ALTER TABLE tasks ADD COLUMN new_owner_id INTEGER")
    op.execute("UPDATE tasks t SET new_owner_id = u.new_id FROM users u WHERE t.owner_id = u.id")
    op.execute("ALTER TABLE tasks DROP CONSTRAINT IF EXISTS tasks_owner_id_fkey")
    op.execute("ALTER TABLE tasks DROP COLUMN owner_id")  # also drops ix_tasks_owner_id
    op.execute("ALTER TABLE tasks RENAME COLUMN new_owner_id TO owner_id")
    op.execute("ALTER TABLE tasks ALTER COLUMN owner_id SET NOT NULL")

    # 3. Swap the users primary key.
    op.execute("ALTER TABLE users DROP CONSTRAINT users_pkey")
    op.execute("ALTER TABLE users DROP COLUMN id")
    op.execute("ALTER TABLE users RENAME COLUMN new_id TO id")
    op.execute("ALTER TABLE users ALTER COLUMN id SET NOT NULL")
    op.execute("ALTER TABLE users ADD PRIMARY KEY (id)")

    # 4. Auto-numbering for new signups continues after the highest id, never below 2.
    op.execute("ALTER TABLE users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (START WITH 2)")
    op.execute(
        "SELECT setval(pg_get_serial_sequence('users', 'id'), GREATEST((SELECT MAX(id) FROM users), 1))"
    )

    # 5. Restore the foreign key and index.
    op.execute(
        "ALTER TABLE tasks ADD CONSTRAINT tasks_owner_id_fkey "
        "FOREIGN KEY (owner_id) REFERENCES users(id) ON DELETE CASCADE"
    )
    op.create_index("ix_tasks_owner_id", "tasks", ["owner_id"])


def downgrade() -> None:
    raise RuntimeError("Converting numeric user IDs back to UUIDs is not supported.")
