"""SQLAlchemy ORM models."""
import enum
import uuid
from datetime import datetime, timezone

from sqlalchemy import (
    Boolean,
    DateTime,
    Enum as SAEnum,
    Float,
    ForeignKey,
    Identity,
    Integer,
    String,
)
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.database import Base


def _uuid() -> str:
    return str(uuid.uuid4())


def _utcnow() -> datetime:
    return datetime.now(timezone.utc)


class Difficulty(str, enum.Enum):
    EASY = "Easy"
    MEDIUM = "Medium"
    HARD = "Hard"
    VERY_HARD = "Very Hard"


class PriorityLevel(str, enum.Enum):
    LOW = "Low"
    MEDIUM = "Medium"
    HIGH = "High"
    CRITICAL = "Critical"


# The main administrator always has user ID 1 (created by app.seed). Normal
# accounts are numbered from 2 upward, so 1 is never handed to anyone else.
ROOT_ADMIN_ID = 1


class User(Base):
    __tablename__ = "users"
    # SQLite (tests): never reuse the ID of a deleted user.
    __table_args__ = {"sqlite_autoincrement": True}

    # Unique, sequential, never reused. Postgres: GENERATED BY DEFAULT AS
    # IDENTITY starting at 2; ID 1 is inserted explicitly for the main admin.
    id: Mapped[int] = mapped_column(Integer, Identity(start=2), primary_key=True)
    name: Mapped[str] = mapped_column(String(120), nullable=False)
    email: Mapped[str] = mapped_column(String(255), unique=True, index=True, nullable=False)
    hashed_password: Mapped[str] = mapped_column(String(255), nullable=False)
    # Admins can see and manage every user's tasks via /admin. Registration
    # never grants admin; it is set by the seeding step or by another admin.
    is_admin: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)
    # Deactivated accounts cannot log in, but their data is kept.
    is_active: Mapped[bool] = mapped_column(Boolean, default=True, nullable=False)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=_utcnow)

    tasks: Mapped[list["Task"]] = relationship(
        "Task", back_populates="owner", cascade="all, delete-orphan"
    )


class Task(Base):
    __tablename__ = "tasks"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=_uuid)
    owner_id: Mapped[int] = mapped_column(
        Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True
    )

    title: Mapped[str] = mapped_column(String(200), nullable=False)
    subject: Mapped[str] = mapped_column(String(120), nullable=False, index=True)
    deadline: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    difficulty: Mapped[Difficulty] = mapped_column(SAEnum(Difficulty), nullable=False)
    estimated_hours: Mapped[float] = mapped_column(Float, nullable=False)

    completed: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)
    completed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)

    # Priority is recomputed server-side (FR-11/FR-13) and persisted so it can be
    # queried/sorted/filtered without recalculating on every read.
    priority_score: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)
    priority_level: Mapped[PriorityLevel] = mapped_column(
        SAEnum(PriorityLevel), nullable=False, default=PriorityLevel.LOW
    )

    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=_utcnow)
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=_utcnow, onupdate=_utcnow
    )

    owner: Mapped["User"] = relationship("User", back_populates="tasks")
